// ExerciseSessionEntityTests.swift
// DomainTests

import XCTest
@testable import Domain

/// Tests for the ExerciseSession entity.
/// Each test verifies a single behaviour (Single Responsibility).
final class ExerciseSessionEntityTests: XCTestCase {

    // MARK: - Initialisation

    func testSessionStoresExerciseId() {
        let exerciseId = UUID()
        let session = ExerciseSession(exerciseId: exerciseId, exerciseTitle: "Tabata", durationSeconds: 120)
        XCTAssertEqual(session.exerciseId, exerciseId)
    }

    func testSessionStoresExerciseTitle() {
        let session = ExerciseSession(exerciseId: UUID(), exerciseTitle: "Sprint", durationSeconds: 60)
        XCTAssertEqual(session.exerciseTitle, "Sprint")
    }

    func testAutoGeneratedIdIsUnique() {
        let a = ExerciseSession(exerciseId: UUID(), exerciseTitle: "A", durationSeconds: 10)
        let b = ExerciseSession(exerciseId: UUID(), exerciseTitle: "A", durationSeconds: 10)
        XCTAssertNotEqual(a.id, b.id)
    }

    func testProvidedIdIsPreserved() {
        let id = UUID()
        let session = ExerciseSession(id: id, exerciseId: UUID(), exerciseTitle: "T", durationSeconds: 30)
        XCTAssertEqual(session.id, id)
    }

    // MARK: - durationMinutes

    func testDurationMinutesIsExactDivision() {
        let session = ExerciseSession(exerciseId: UUID(), exerciseTitle: "T", durationSeconds: 120)
        XCTAssertEqual(session.durationMinutes, 2)
    }

    func testDurationMinutesTruncatesRemainder() {
        let session = ExerciseSession(exerciseId: UUID(), exerciseTitle: "T", durationSeconds: 90)
        XCTAssertEqual(session.durationMinutes, 1)
    }

    func testDurationMinutesIsZeroWhenUnderOneMinute() {
        let session = ExerciseSession(exerciseId: UUID(), exerciseTitle: "T", durationSeconds: 59)
        XCTAssertEqual(session.durationMinutes, 0)
    }

    // MARK: - Equatable

    func testSessionsWithSameIdAreEqual() {
        let id = UUID()
        let exerciseId = UUID()
        let date = Date(timeIntervalSince1970: 0)
        let a = ExerciseSession(id: id, exerciseId: exerciseId, exerciseTitle: "A", completedAt: date, durationSeconds: 100)
        let b = ExerciseSession(id: id, exerciseId: exerciseId, exerciseTitle: "A", completedAt: date, durationSeconds: 100)
        XCTAssertEqual(a, b)
    }

    func testSessionsWithDifferentIdsAreNotEqual() {
        let exerciseId = UUID()
        let a = ExerciseSession(exerciseId: exerciseId, exerciseTitle: "A", durationSeconds: 100)
        let b = ExerciseSession(exerciseId: exerciseId, exerciseTitle: "A", durationSeconds: 100)
        XCTAssertNotEqual(a, b)
    }
}
