// ExerciseEntityTests.swift
// DomainTests

import XCTest
@testable import Domain

/// Tests for the Exercise entity.
/// Each test verifies a single behaviour (Single Responsibility).
final class ExerciseEntityTests: XCTestCase {

    // MARK: - Initialisation

    func testDefaultWarmupIsAppliedWhenNotProvided() {
        let exercise = Exercise(title: "Workout", activeSeconds: 30, restSeconds: 10, repetitions: 4)
        XCTAssertEqual(exercise.warmupSeconds, 5)
    }

    func testCustomWarmupIsPreserved() {
        let exercise = Exercise(title: "Workout", warmupSeconds: 10, activeSeconds: 30, restSeconds: 10, repetitions: 4)
        XCTAssertEqual(exercise.warmupSeconds, 10)
    }

    func testRecoveryIsNilByDefault() {
        let exercise = Exercise(title: "Workout", activeSeconds: 30, restSeconds: 10, repetitions: 4)
        XCTAssertNil(exercise.recoverySeconds)
    }

    func testCustomRecoveryIsPreserved() {
        let exercise = Exercise(title: "Workout", activeSeconds: 30, restSeconds: 10, repetitions: 4, recoverySeconds: 60)
        XCTAssertEqual(exercise.recoverySeconds, 60)
    }

    func testProvidedIdIsPreserved() {
        let id = UUID()
        let exercise = Exercise(id: id, title: "Workout", activeSeconds: 30, restSeconds: 10, repetitions: 4)
        XCTAssertEqual(exercise.id, id)
    }

    func testAutoGeneratedIdIsUnique() {
        let first = Exercise(title: "A", activeSeconds: 20, restSeconds: 10, repetitions: 4)
        let second = Exercise(title: "A", activeSeconds: 20, restSeconds: 10, repetitions: 4)
        XCTAssertNotEqual(first.id, second.id)
    }

    // MARK: - totalDurationSeconds

    func testTotalDurationWithoutRecovery() {
        // 5 + (20 + 10) * 4 = 5 + 120 = 125
        let exercise = Exercise(title: "T", warmupSeconds: 5, activeSeconds: 20, restSeconds: 10, repetitions: 4)
        XCTAssertEqual(exercise.totalDurationSeconds, 125)
    }

    func testTotalDurationWithRecovery() {
        // 5 + (30 + 10) * 4 + 60 = 5 + 160 + 60 = 225
        let exercise = Exercise(title: "T", warmupSeconds: 5, activeSeconds: 30, restSeconds: 10, repetitions: 4, recoverySeconds: 60)
        XCTAssertEqual(exercise.totalDurationSeconds, 225)
    }

    func testTotalDurationNoWarmup() {
        // 0 + (20 + 10) * 3 = 90
        let exercise = Exercise(title: "T", warmupSeconds: 0, activeSeconds: 20, restSeconds: 10, repetitions: 3)
        XCTAssertEqual(exercise.totalDurationSeconds, 90)
    }

    func testTotalDurationSingleRepetition() {
        // 5 + (40 + 20) * 1 = 65
        let exercise = Exercise(title: "T", warmupSeconds: 5, activeSeconds: 40, restSeconds: 20, repetitions: 1)
        XCTAssertEqual(exercise.totalDurationSeconds, 65)
    }

    // MARK: - Equatable & Hashable

    func testExercisesWithIdenticalFieldsAreEqual() {
        let id = UUID()
        let date = Date(timeIntervalSince1970: 0)
        let a = Exercise(id: id, title: "A", warmupSeconds: 5, activeSeconds: 20, restSeconds: 10, repetitions: 4, recoverySeconds: nil, createdAt: date)
        let b = Exercise(id: id, title: "A", warmupSeconds: 5, activeSeconds: 20, restSeconds: 10, repetitions: 4, recoverySeconds: nil, createdAt: date)
        XCTAssertEqual(a, b)
    }

    func testExercisesWithDifferentIdsAreNotEqual() {
        let a = Exercise(title: "A", activeSeconds: 20, restSeconds: 10, repetitions: 4)
        let b = Exercise(title: "A", activeSeconds: 20, restSeconds: 10, repetitions: 4)
        XCTAssertNotEqual(a, b)
    }

    func testExerciseHashIsBasedOnId() {
        let id = UUID()
        let a = Exercise(id: id, title: "A", activeSeconds: 20, restSeconds: 10, repetitions: 4)
        let b = Exercise(id: id, title: "B", activeSeconds: 99, restSeconds: 1, repetitions: 1)
        XCTAssertEqual(a.hashValue, b.hashValue)
    }
}
