// ScheduleEntityTests.swift
// DomainTests

import XCTest
@testable import Domain

/// Tests for Schedule, DaySchedule, and DayOfWeek entities.
/// Each test verifies a single behaviour (Single Responsibility).
final class ScheduleEntityTests: XCTestCase {

    // MARK: - DayOfWeek

    func testAllDayOfWeekCasesExist() {
        XCTAssertEqual(DayOfWeek.allCases.count, 7)
    }

    func testDayOfWeekCalendarWeekdayMatchesRawValue() {
        for day in DayOfWeek.allCases {
            XCTAssertEqual(day.calendarWeekday, day.rawValue)
        }
    }

    func testSundayIsWeekday1() {
        XCTAssertEqual(DayOfWeek.sunday.calendarWeekday, 1)
    }

    func testSaturdayIsWeekday7() {
        XCTAssertEqual(DayOfWeek.saturday.calendarWeekday, 7)
    }

    func testDisplayNames() {
        XCTAssertEqual(DayOfWeek.sunday.displayName, "Sunday")
        XCTAssertEqual(DayOfWeek.monday.displayName, "Monday")
        XCTAssertEqual(DayOfWeek.tuesday.displayName, "Tuesday")
        XCTAssertEqual(DayOfWeek.wednesday.displayName, "Wednesday")
        XCTAssertEqual(DayOfWeek.thursday.displayName, "Thursday")
        XCTAssertEqual(DayOfWeek.friday.displayName, "Friday")
        XCTAssertEqual(DayOfWeek.saturday.displayName, "Saturday")
    }

    func testShortNamesAreThreeCharacters() {
        for day in DayOfWeek.allCases {
            XCTAssertEqual(day.shortName.count, 3)
        }
    }

    func testShortNameIsPrefixOfDisplayName() {
        for day in DayOfWeek.allCases {
            XCTAssertTrue(day.displayName.hasPrefix(day.shortName))
        }
    }

    // MARK: - DaySchedule

    func testReminderTimeFormattedWithLeadingZeros() {
        let daySchedule = DaySchedule(dayOfWeek: .monday, reminderHour: 8, reminderMinute: 5)
        XCTAssertEqual(daySchedule.reminderTimeFormatted, "08:05")
    }

    func testReminderTimeFormattedMidnight() {
        let daySchedule = DaySchedule(dayOfWeek: .sunday, reminderHour: 0, reminderMinute: 0)
        XCTAssertEqual(daySchedule.reminderTimeFormatted, "00:00")
    }

    func testReminderTimeFormattedEndOfDay() {
        let daySchedule = DaySchedule(dayOfWeek: .friday, reminderHour: 23, reminderMinute: 59)
        XCTAssertEqual(daySchedule.reminderTimeFormatted, "23:59")
    }

    func testReminderTimeFormattedNoon() {
        let daySchedule = DaySchedule(dayOfWeek: .wednesday, reminderHour: 12, reminderMinute: 30)
        XCTAssertEqual(daySchedule.reminderTimeFormatted, "12:30")
    }

    // MARK: - Schedule

    func testScheduleStoresExerciseId() {
        let exerciseId = UUID()
        let schedule = Schedule(exerciseId: exerciseId, daySchedules: [])
        XCTAssertEqual(schedule.exerciseId, exerciseId)
    }

    func testScheduleEmptyDaySchedules() {
        let schedule = Schedule(exerciseId: UUID(), daySchedules: [])
        XCTAssertTrue(schedule.daySchedules.isEmpty)
    }

    func testSchedulePreservesMultipleDaySchedules() {
        let days: [DaySchedule] = [
            DaySchedule(dayOfWeek: .monday, reminderHour: 7, reminderMinute: 0),
            DaySchedule(dayOfWeek: .wednesday, reminderHour: 18, reminderMinute: 30),
            DaySchedule(dayOfWeek: .friday, reminderHour: 6, reminderMinute: 45)
        ]
        let schedule = Schedule(exerciseId: UUID(), daySchedules: days)
        XCTAssertEqual(schedule.daySchedules.count, 3)
        XCTAssertEqual(schedule.daySchedules[1].dayOfWeek, .wednesday)
    }

    func testAutoGeneratedIdIsUnique() {
        let id = UUID()
        let a = Schedule(exerciseId: id, daySchedules: [])
        let b = Schedule(exerciseId: id, daySchedules: [])
        XCTAssertNotEqual(a.id, b.id)
    }

    func testProvidedIdIsPreserved() {
        let scheduleId = UUID()
        let schedule = Schedule(id: scheduleId, exerciseId: UUID(), daySchedules: [])
        XCTAssertEqual(schedule.id, scheduleId)
    }
}
